id = "notist"
name = "Notist"
description = "Notist language support with syntax highlighting, diagnostics, completion, and navigation."
version = "0.1.0"
schema_version = 1
authors = ["Notist contributors"]
repository = "https://github.com/AzurIce/zed-notist"

[language_servers.notist]
name = "Notist Language Server"
languages = ["Notist"]

[grammars.notist]
repository = "https://github.com/AzurIce/tree-sitter-notist"
rev = "a145fd379a445da3dc4372562db4e777179debb6"
