name = "Notist"
grammar = "notist"
path_suffixes = ["not"]
tab_size = 2
autoclose_before = ";:.,=}])>!"
brackets = [
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["string"] },
]
